import { ProductType } from "../types/product.model";

export const EXAMPLE_PRODUCTS: ProductType[] = [
  {
    id: 1,
    name: "Poco X3 Pro 6 ГБ/128 ГБ синий",
    description: "Смартфон Poco X3 Pro с 6 ГБ RAM и 128 ГБ встроенной памяти, 120 Гц экран, NFC, мощный Snapdragon 860.",
    price: 119990,
    rating: 4.9,
    link: "https://kaspi.kz/shop/p/poco-x3-pro-6-128gb-sinii-101372083/?c=352410000",
    image: "https://resources.cdn-kaspi.kz/img/m/p/h63/hee/64107550375966.jpg?format=gallery-medium",
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h63/hee/64107550375966.jpg?format=gallery-medium",
             "https://resources.cdn-kaspi.kz/img/m/p/h34/h16/64107555749918.jpg?format=gallery-medium",
             "https://resources.cdn-kaspi.kz/img/m/p/hda/hf3/64107559813150.jpg?format=gallery-medium"],
    categoryId: 1,
    likes: 0
  },
  {
    id: 2,
    name: "Apple iPhone 16 Pro Max 256Gb серебристый",
    description: "Флагманский смартфон Apple с 256 ГБ памяти, OLED-дисплей, улучшенная камера и высокая производительность.",
    price: 799990,
    rating: 4.8,
    link: "https://kaspi.kz/shop/p/apple-iphone-16-pro-max-256gb-serebristyi-123890752/",
    image: "",
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h74/ha7/87295492882462.png?format=gallery-medium",
             "https://resources.cdn-kaspi.kz/img/m/p/h98/hb6/87295492915230.png?format=gallery-medium",
             "https://resources.cdn-kaspi.kz/img/m/p/haa/hc9/87295492947998.png?format=gallery-medium"],
    categoryId: 1,
    likes: 0
  },
  {
    id: 3,
    name: "Samsung Galaxy A53 5G 6 ГБ/128 ГБ черный",
    description: "Смартфон с поддержкой 5G, 6 ГБ оперативной памяти, 128 ГБ хранения и AMOLED-экраном.",
    price: 179990,
    rating: 4.7,
    link: "https://kaspi.kz/shop/p/samsung-galaxy-a53-5g-6-gb-128-gb-chernyi-104253225/",
    image: "",
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h64/h86/86029574406174.png?format=gallery-medium",
             "https://resources.cdn-kaspi.kz/img/m/p/h72/he3/86029574438942.png?format=gallery-medium",
             "https://resources.cdn-kaspi.kz/img/m/p/h36/hf9/86029574471710.png?format=gallery-medium"],
    categoryId: 1,
    likes: 0
  },
  {
    id: 4,
    name: "Xiaomi 14 12 ГБ/512 ГБ черный",
    description: "Мощный смартфон с 12 ГБ RAM, 512 ГБ памяти, AMOLED-экраном и процессором Snapdragon 8 Gen 3.",
    price:499990,
    rating: 4.9,
    link: "https://kaspi.kz/shop/p/xiaomi-14-12-gb-512-gb-chernyi-117244078/",
    image: "",
    images: ["https://resources.cdn-kaspi.kz/img/m/p/h07/h3d/85370041991198.jpg?format=gallery-medium",
             "https://resources.cdn-kaspi.kz/img/m/p/he0/h6d/85370042056734.jpg?format=gallery-medium",
             "https://resources.cdn-kaspi.kz/img/m/p/pdc/p73/64539467.png?format=gallery-medium"],
    categoryId: 1,
    likes: 0
  },
  {
    id: 5,
    name: "BQ BQ-4585 Fox View коричневый",
    description: "Бюджетный смартфон с компактным экраном и базовым функционалом для повседневных задач.",
    price: 24990,
    rating: 4.3,
    link: "https://kaspi.kz/shop/p/bq-bq-4585-fox-view-korichnevyi-1004086/?c=352410000",
    image: "",
    images: ["", "", ""],
    categoryId: 1,
    likes: 0
  },
  {
      id: 6,
      name: 'Apple AirPods Pro (2nd gen)',
      description: 'AirPods are a MUST.',
      price: 129990,
      rating: 4.9,
      image: 'assets/images/airpods.jpg',
      images: ['','',''],
      link: 'https://kaspi.kz/shop/p/naushniki-apple-airpods-pro-2nd-generation-with-wireless-magsafe-charging-case-belyi-113677582/?c=750000000',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 7,
      name: 'Apple AirPods 4',
      description: 'Coolest wireless AirPods.',
      price: 89990,
      rating: 4.7,
      image: 'assets/images/airpods4.jpg',
      images: ['','',''],
      link: 'https://kaspi.kz/shop/p/naushniki-apple-airpods-4-belyi-124333372/?c=750000000',
      categoryId: 5,
      likes: 0,
    },
    {
      id: 8,
      name: 'Sony WH-1000XM4',
      description: 'Legendary noise-cancelling headphones.',
      price: 373323,
      rating: 4.8,
      image: 'assets/images/sony.jpg',
      images: ['','',''],
      link: 'https://kaspi.kz/shop/p/naushniki-sony-wh-1000xm4-serebristyi-100509735/?c=750000000',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 9,
      name: 'Marshall Major IV',
      description: 'Iconic Marshall sound and design.',
      price: 543447,
      rating: 4.9,
      image: 'assets/images/marshall.jpg',
      images: ['','',''],
      link: 'https://kaspi.kz/shop/p/naushniki-marshall-major-iv-jbl-clip-4-sinii-chernyi-131793119/?c=750000000',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 10,
      name: 'JBL Tune 720BT',
      description: 'Comfortable wireless headphones with punchy bass.',
      price: 59990,
      rating: 4.5,
      image: 'assets/images/jbl-720.jpg',
      images: ['','',''],
      link: 'https://kaspi.kz/shop/search/?text=jbl%20tune%20720bt',
      categoryId: 3,
      likes: 0,
    },
    {
      id: 11,
      name: 'Apple MacBook Air 13 (2022) 16GB/256GB',
      description: 'Perfect for study, work, and coffee shops.',
      price: 543960,
      rating: 5.0,
      image: 'assets/images/macbook.jpg',
      images: ['','',''],
      link: 'https://kaspi.kz/shop/p/apple-macbook-air-13-2020-13-3-8-gb-ssd-256-gb-macos-mgn63ru-a-101182724/?c=750000000',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 12,
      name: 'Apple MacBook Pro 14 M3',
      description: 'Powerful Pro notebook for creators.',
      price: 899990,
      rating: 4.9,
      image: 'assets/images/macbook-pro-14.jpg',
      images: ['','',''],
      link: 'https://kaspi.kz/shop/search/?text=macbook%20pro%2014%20m3',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 13,
      name: 'ASUS ROG Strix G15',
      description: 'Gaming laptop with high refresh display.',
      price: 679990,
      rating: 4.7,
      image: 'assets/images/asus-rog-g15.jpg',
      images: ['','',''],
      link: 'https://kaspi.kz/shop/search/?text=asus%20rog%20strix%20g15',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 14,
      name: 'Lenovo IdeaPad 3',
      description: 'Affordable everyday laptop.',
      price: 229990,
      rating: 4.4,
      image: 'assets/images/lenovo-ideapad-3.jpg',
      images: ['', '', ''],
      link: 'https://kaspi.kz/shop/search/?text=lenovo%20ideapad%203',
      categoryId: 2,
      likes: 0,
    },
    {
      id: 15,
      name: 'Apple iPad 10.9 (10th gen)',
      description: 'Bright tablet for media and notes.',
      price: 289990,
      rating: 4.8,
      image: 'assets/images/ipad-10.jpg',
      images: ['', '', ''],
      link: 'https://kaspi.kz/shop/search/?text=ipad%2010%20gen',
      categoryId: 2,
      likes: 0,
    },
{
  id: 16,
  name: "Laptops Example Model D",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-d/",
  image: "",
  images: ["", "", ""],
  categoryId: 2,
  likes: 0
},
{
  id: 17,
  name: "N-Tech Desktop Computer 056",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/n-tech-desktop-computer-056-sinii-102487935/",
  image: "",
  images: ["", "", ""],
  categoryId: 2,
  likes: 0
},
{
  id: 18,
  name: "Laptops Example Model A",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-a/",
  image: "",
  images: ["", "", ""],
  categoryId: 2,
  likes: 0
},
{
  id: 19,
  name: "Laptops Example Model B",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-b/",
  image: "",
  images: ["", "", ""],
  categoryId: 2,
  likes: 0
},
{
  id: 20,
  name: "Laptops Example Model C",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-c/",
  image: "",
  images: ["", "", ""],
  categoryId: 2,
  likes: 0
}
];