import { ProductType } from "../types/product.model";

export const EXAMPLE_PRODUCTS: ProductType[] = [
  {
    id: 1,
    name: "Poco X3 Pro 6 ГБ/128 ГБ синий",
    description: "Смартфон Poco X3 Pro с 6 ГБ RAM и 128 ГБ встроенной памяти, 120 Гц экран, NFC, мощный Snapdragon 860.",
    price: 119990,
    rating: 4.9,
    link: "https://kaspi.kz/shop/p/poco-x3-pro-6-128gb-sinii-101372083/?c=352410000",
    image: "",
    images: ["", "", ""],
    categoryId: 1,
    likes: 0
  },
  {
    id: 2,
    name: "Apple iPhone 16 Pro Max 256Gb серебристый",
    description: "Флагманский смартфон Apple с 256 ГБ памяти, OLED-дисплей, улучшенная камера и высокая производительность.",
    price: 799990,
    rating: 4.8,
    link: "https://kaspi.kz/shop/p/apple-iphone-16-pro-max-256gb-serebristyi-123890752/",
    image: "",
    images: ["", "", ""],
    categoryId: 1,
    likes: 0
  },
  {
    id: 3,
    name: "Samsung Galaxy A53 5G 6 ГБ/128 ГБ черный",
    description: "Смартфон с поддержкой 5G, 6 ГБ оперативной памяти, 128 ГБ хранения и AMOLED-экраном.",
    price: 179990,
    rating: 4.7,
    link: "https://kaspi.kz/shop/p/samsung-galaxy-a53-5g-6-gb-128-gb-chernyi-104253225/",
    image: "",
    images: ["", "", ""],
    categoryId: 1,
    likes: 0
  },
  {
    id: 4,
    name: "Xiaomi 14 12 ГБ/512 ГБ черный",
    description: "Мощный смартфон с 12 ГБ RAM, 512 ГБ памяти, AMOLED-экраном и процессором Snapdragon 8 Gen 3.",
    price:499990,
    rating: 4.9,
    link: "https://kaspi.kz/shop/p/xiaomi-14-12-gb-512-gb-chernyi-117244078/",
    image: "",
    images: ["", "", ""],
    categoryId: 1,
    likes: 0
  },
  {
    id: 5,
    name: "BQ BQ-4585 Fox View коричневый",
    description: "Бюджетный смартфон с компактным экраном и базовым функционалом для повседневных задач.",
    price: 24990,
    rating: 4.3,
    link: "https://kaspi.kz/shop/p/bq-bq-4585-fox-view-korichnevyi-1004086/?c=352410000",
    image: "",
    images: ["", "", ""],
    categoryId: 1,
    likes: 0
  },
  {
  id: 6,
  name: "N-Tech Desktop Computer 056",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/n-tech-desktop-computer-056-sinii-102487935/",
  image: "",
  images: ["", "", ""],
  categoryId: 4,
  likes: 0
},
{
  id: 7,
  name: "Системный блок Example Model A",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-a/",
  image: "",
  images: ["", "", ""],
  categoryId: 4,
  likes: 0
},
{
  id: 8,
  name: "Системный блок Example Model B",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-b/",
  image: "",
  images: ["", "", ""],
  categoryId: 4,
  likes: 0
},
{
  id: 9,
  name: "Системный блок Example Model C",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-c/",
  image: "",
  images: ["", "", ""],
  categoryId: 4,
  likes: 0
},
{
  id: 10,
  name: "Headphones Example Model D",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-d/",
  image: "",
  images: ["", "", ""],
  categoryId: 4,
  likes: 0
},
{
  id: 11,
  name: "N-Tech Desktop Computer 056",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/n-tech-desktop-computer-056-sinii-102487935/",
  image: "",
  images: ["", "", ""],
  categoryId: 3,
  likes: 0
},
{
  id: 12,
  name: "Headphones Example Model A",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-a/",
  image: "",
  images: ["", "", ""],
  categoryId: 3,
  likes: 0
},
{
  id: 13,
  name: "Headphones Example Model B",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-b/",
  image: "",
  images: ["", "", ""],
  categoryId: 3,
  likes: 0
},
{
  id: 14,
  name: "Headphones Example Model C",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-c/",
  image: "",
  images: ["", "", ""],
  categoryId: 3,
  likes: 0
},
{
  id: 15,
  name: "Headphones Example Model D",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-d/",
  image: "",
  images: ["", "", ""],
  categoryId: 3,
  likes: 0
},
{
  id: 16,
  name: "Laptops Example Model D",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-d/",
  image: "",
  images: ["", "", ""],
  categoryId: 2,
  likes: 0
},
{
  id: 17,
  name: "N-Tech Desktop Computer 056",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/n-tech-desktop-computer-056-sinii-102487935/",
  image: "",
  images: ["", "", ""],
  categoryId: 2,
  likes: 0
},
{
  id: 18,
  name: "Laptops Example Model A",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-a/",
  image: "",
  images: ["", "", ""],
  categoryId: 2,
  likes: 0
},
{
  id: 19,
  name: "Laptops Example Model B",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-b/",
  image: "",
  images: ["", "", ""],
  categoryId: 2,
  likes: 0
},
{
  id: 20,
  name: "Laptops Example Model C",
  description: "",
  price: 0,
  rating: 0,
  link: "https://kaspi.kz/shop/p/example-model-c/",
  image: "",
  images: ["", "", ""],
  categoryId: 2,
  likes: 0
}
];